### ISSUE TITLE
Run toc-me on wiki pages?

### ISSUE THREAD

**Issue by jasonkarns** [pholleran/toc-me#21]
Is it possible to configure toc-me to subscribe to gollum events so that it can maintain Tables of Contents on wiki pages?

**Comment by pholleran** [comment]
@jasonkarns - As it is presently implemented I don't think so.

There are some unique aspects of how wikis are handled that will present a challenge:

First, the repository returned by the [gollum event](https://developer.github.com/v3/activity/events/types/#gollumevent) is for the code repo, not the [wiki repo](https://help.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally). So any reference to the repo in the `context` object would need to be modified.

Second, the existing logic relies upon `push` event to [provide the commit](https://github.com/pholleran/toc-me/blob/master/index.js#L15-L18). Since there is no way to directly provide the commit this logic cannot be used.

Third, I am not sure if the API calls to the main repo work on wiki repos. 

If you do give it a go, I'd recommend running `markdown-toc` in a different manner for wikis. Just spit-balling here, but this approach would get rid of the differences between how main repos and wiki repos are handled.

1. Create a GitHub Action or Probot app (or a new route in this probot app) that listens for Gollum events
2. Have the action clone the wiki repository following this [syntax](https://help.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally) to a scratch workspace
3. Run `markdown-toc` on all markdown files in the repo and commit any changes.
4. Push the wiki repo back to GitHub
